version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo Installing dependencies
      - composer --version
      - composer install --no-dev --prefer-dist --optimize-autoloader
      - echo Installing MySQL client
      - if command -v yum >/dev/null; then yum install -y mysql; fi
      - if command -v apt-get >/dev/null; then apt-get update && apt-get install -y mysql-client; fi

  pre_build:
    commands:
      - echo Starting pre-build phase...
      - sudo chmod -R 777 bootstrap/cache
      - sudo chmod -R 777 storage
      - php artisan config:clear
      - echo Testing MySQL connection...
      - echo DB_HOST=$DB_HOST
      - echo DB_USERNAME=$DB_USERNAME
      - echo DB_PASSWORD=$DB_PASSWORD
      - mysql -h $DB_HOST -u $DB_USERNAME -p$DB_PASSWORD -e "SHOW DATABASES;" || echo "Failed to connect to database"

  build:
    commands:
      - echo Building the Laravel application...
      - php artisan migrate
      - php artisan optimize

  post_build:
    commands:
      - echo Build complete.

artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - vendor/**/*
    - node_modules/**/*

