version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo Installing dependencies
      - composer --version
      - composer install --no-dev --prefer-dist --optimize-autoloader

  pre_build:
    commands:
      - echo Starting pre-build phase...
      - sudo chmod -R 777 bootstrap/cache
      - sudo chmod -R 777 storage
      - php artisan config:clear

  build:
    commands:
      - echo Building the Laravel application...
      - php artisan migrate
      - php artisan optimize

  post_build:
    commands:
      - echo Build complete.

artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - vendor/**/*
    - node_modules/**/*

